'use strict';
const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n};
const media=matchMedia('(prefers-color-scheme: dark)');
function appearance(){document.body.classList.toggle('dark',$('theme').value==='Dark'||$('theme').value==='System'&&media.matches)}
try{$('theme').value=localStorage.getItem('canopy-theme')||'System'}catch{}
appearance();media.addEventListener('change',appearance);$('theme').onchange=()=>{appearance();try{localStorage.setItem('canopy-theme',$('theme').value)}catch{}};
function view(id){document.querySelectorAll('.view').forEach(n=>n.hidden=n.id!==id);document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('pageTitle').textContent={permissions:'See who has access.',overview:'Your collected inventory.',coverage:'Know where the view ends.',exports:'Evidence you can carry.'}[id]}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>view(n.dataset.view));$('coverageLink').onclick=()=>view('coverage');$('openPermissions').onclick=()=>view('permissions');$('exportTop').onclick=()=>$('exportDialog').showModal();$('closeDialog').onclick=()=>$('exportDialog').close();
const sample={schemaVersion:'0.2-delegated',synthetic:true,completedAt:'2026-09-30T14:00:00Z',scope:{siteUrl:'https://fabrikam.sharepoint.com/sites/Demo',library:'Documents',depth:'Synthetic library and folders'},state:'partial',resources:[{id:'web:demo',type:'web',title:'Demo',url:'/sites/Demo',hasUniqueRoleAssignments:true,sourceResourceId:'web:demo'},{id:'list:demo',type:'library',title:'Documents',url:'/sites/Demo/Shared Documents',hasUniqueRoleAssignments:false,sourceResourceId:'web:demo'},{id:'folder:private',type:'folder',title:'Private',url:'/sites/Demo/Shared Documents/Private',parentResourceId:'list:demo',hasUniqueRoleAssignments:true,sourceResourceId:'folder:private'},{id:'folder:child',type:'folder',title:'Child',url:'/sites/Demo/Shared Documents/Private/Child',parentResourceId:'folder:private',hasUniqueRoleAssignments:false,sourceResourceId:'folder:private'}],grants:[{resourceId:'web:demo',principal:{id:'3',title:'Demo Members',type:'SharePointGroup',loginName:'Demo Members'},roles:[{name:'Edit'}]},{resourceId:'folder:private',principal:{id:'4',title:'Demo Owners',type:'SharePointGroup',loginName:'Demo Owners'},roles:[{name:'Full Control'}]}],sharePointGroups:[{id:'3',state:'observed',members:[{id:'10',title:'Team members',type:'SecurityGroup',loginName:'c:0o.c|federateddirectoryclaimprovider|11111111-1111-1111-1111-111111111111'}]},{id:'4',state:'observed',members:[{id:'11',title:'Team owners',type:'SecurityGroup',loginName:'c:0o.c|federateddirectoryclaimprovider|11111111-1111-1111-1111-111111111111_o'}]}],directoryGroups:[{id:'11111111-1111-1111-1111-111111111111',relationship:'members',displayName:'Demo team',state:'observed',reason:'Synthetic membership',members:[{id:'person:member',displayName:'Sample Member',userPrincipalName:'member@example.invalid',type:'#microsoft.graph.user'}]},{id:'11111111-1111-1111-1111-111111111111',relationship:'owners',displayName:'Demo team',state:'observed',reason:'Synthetic owners',members:[{id:'person:owner',displayName:'Sample Owner',type:'#microsoft.graph.user'}]}],coverage:[{operation:'Files and sharing links',state:'notRequested',reason:'Not collected in this sample.'}]};
let audit=sample,selectedId='list:demo',selectedGrant=0,filter='all';
function validate(data){
 if(!data||data.schemaVersion!=='0.2-delegated'||!data.scope||typeof data.scope.siteUrl!=='string')throw Error('Expected a 365Canopy 0.2-delegated audit snapshot.');
 for(const key of ['resources','grants','sharePointGroups','directoryGroups','coverage'])if(!Array.isArray(data[key])||data[key].length>50000)throw Error('Invalid or oversized '+key+' collection.');
 const ids=new Set();for(const r of data.resources){if(!r||typeof r.id!=='string'||typeof r.url!=='string'||ids.has(r.id))throw Error('Invalid or duplicate resource.');ids.add(r.id)}
 for(const g of data.grants)if(!g||typeof g.resourceId!=='string'||!g.principal||!Array.isArray(g.roles))throw Error('Invalid grant record.');
 for(const g of [...data.sharePointGroups,...data.directoryGroups])if(!g||typeof g.id!=='string'||!Array.isArray(g.members))throw Error('Invalid membership record.');
 return data;
}
const tree=document.querySelector('.tree');tree.replaceChildren(el('h2','Resource tree'),el('small','Search collected resource paths'));
const search=el('input');search.id='search';search.placeholder='Find a resource…';search.setAttribute('aria-label','Search collected resources');tree.append(search);
const treeNodes=el('div');tree.append(treeNodes);
const loadInput=el('input');loadInput.type='file';loadInput.accept='.json,application/json';loadInput.id='auditFile';loadInput.setAttribute('aria-label','Open audit JSON');
const loadLabel=el('label','Open audit JSON');loadLabel.htmlFor='auditFile';loadLabel.append(loadInput);
const loadStatus=el('p','Local import only. Snapshot contents stay in this browser.','muted');loadStatus.setAttribute('role','status');
const header=document.querySelector('.head');const loadBox=el('div');loadBox.append(loadLabel,loadStatus);header.after(loadBox);
document.querySelector('.bottom p').textContent='Local audit viewer · no tenant connection';
document.querySelector('.filters').replaceChildren();for(const [key,title]of [['all','All grants'],['external','Guests'],['unresolved','Membership gaps']]){const b=el('button',title);b.dataset.filter=key;b.onclick=()=>{filter=key;selectedGrant=0;renderResource()};document.querySelector('.filters').append(b)}
loadInput.onchange=async()=>{const file=loadInput.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('Snapshot exceeds the 20 MB local import limit.');const next=validate(JSON.parse(await file.text()));audit=next;selectedId=audit.resources[0]?.id;selectedGrant=0;filter='all';loadStatus.textContent='Loaded '+file.name+' locally.';renderAudit()}catch(e){loadStatus.textContent='Import failed: '+e.message+' Previous snapshot retained.'}finally{loadInput.value=''}};
function directoryClaim(login){const m=String(login||'').match(/^c:(?:0t\.c\|tenant\||0o\.c\|federateddirectoryclaimprovider\|)([\da-f]{8}(?:-[\da-f]{4}){3}-[\da-f]{12})(_o)?$/i);return m?{id:m[1].toLowerCase(),relationship:m[2]?'owners':'members'}:null}
function directoryGroup(id,relationship){return audit.directoryGroups.find(g=>g.id.toLowerCase()===id.toLowerCase()&&(g.relationship||'members')===relationship)}
function hasGap(p,seen=new Set()){
 if(p.type==='SharePointGroup'){const g=audit.sharePointGroups.find(g=>g.id===p.id);return !g||g.state!=='observed'||g.members.some(m=>hasGap(m,new Set(seen)))}
 const claim=directoryClaim(p.loginName);if(claim)return directoryGap(claim.id,claim.relationship,seen);return false;
}
function directoryGap(id,relationship,seen){const key=id+':'+relationship;if(seen.has(key))return false;seen.add(key);const g=directoryGroup(id,relationship);return !g||g.state!=='observed'||g.members.some(m=>m.type==='#microsoft.graph.group'?directoryGap(m.id,'members',seen):!m.displayName&&!m.userPrincipalName)}
function showDirectory(container,id,relationship,seen){
 const key=id+':'+relationship;const g=directoryGroup(id,relationship);const d=el('details');d.open=true;d.append(el('summary',(g?.displayName||id)+' · '+relationship));container.append(d);
 if(seen.has(key)){d.append(el('p','Cycle detected; previously shown group.','muted'));return}const branch=new Set(seen);branch.add(key);
 if(!g){d.append(el('p','Not collected. People unknown.','muted'));return}d.append(el('small',g.state+' · '+(g.reason||'')));
 for(const m of g.members){if(m.type==='#microsoft.graph.group')showDirectory(d,m.id,'members',branch);else d.append(el('div',(m.displayName||m.userPrincipalName||m.id)+' · '+(m.userPrincipalName||'identity details unavailable'),'member'))}
 if(!g.members.length)d.append(el('p',g.state==='observed'?'No people returned by this relationship query.':'People unknown.'));
}
function showPrincipal(container,p){
 if(p.type==='SharePointGroup'){const g=audit.sharePointGroups.find(g=>g.id===p.id);if(!g){container.append(el('p','SharePoint group membership not collected.'));return}container.append(el('small','Classic SharePoint group · '+g.state));for(const m of g.members){const d=el('details');d.open=true;d.append(el('summary',m.title||m.loginName||m.id));container.append(d);const c=directoryClaim(m.loginName);if(c)showDirectory(d,c.id,c.relationship,new Set());else d.append(el('div',m.loginName||m.title||m.id,'member'))}if(!g.members.length)container.append(el('p',g.state==='observed'?'No direct members returned.':'Members unknown.'));return}
 const c=directoryClaim(p.loginName);if(c)showDirectory(container,c.id,c.relationship,new Set());else container.append(el('div',p.loginName||p.title||p.id,'member'));
}
function renderTree(){treeNodes.replaceChildren();const byId=new Map(audit.resources.map(r=>[r.id,r]));let count=0;for(const r of audit.resources){if(!String(r.url+' '+r.title).toLowerCase().includes(search.value.toLowerCase()))continue;const b=el('button',(r.type==='folder'?'▱ ':r.type==='library'?'▧ ':'▣ ')+(r.title||r.id),'node'+(r.id===selectedId?' selected':''));b.title=r.url;let depth=0,parent=r.parentResourceId||(r.type==='library'?audit.resources.find(n=>n.type==='web')?.id:null);const seen=new Set([r.id]);while(parent&&byId.has(parent)&&!seen.has(parent)&&depth<20){seen.add(parent);depth++;parent=byId.get(parent).parentResourceId}b.style.paddingLeft=(9+depth*14)+'px';b.onclick=()=>{selectedId=r.id;selectedGrant=0;renderTree();renderResource()};treeNodes.append(b);count++}if(!count)treeNodes.append(el('p','No matching collected resources.'))}search.oninput=renderTree;
function renderResource(){
 const r=audit.resources.find(r=>r.id===selectedId);$('grants').replaceChildren();$('members').replaceChildren();if(!r){$('resourceTitle').textContent='No resources collected';$('principal').textContent='No evidence';return}
 $('resourceTitle').textContent=r.title||r.id;document.querySelector('.crumb').textContent=r.url;$('resourceNote').textContent=r.type+' · '+(r.hasUniqueRoleAssignments?'unique permissions':'inherits permissions');$('scopePill').textContent=r.hasUniqueRoleAssignments?'Inheritance broken':r.sourceResourceId?'Inherited from '+(audit.resources.find(n=>n.id===r.sourceResourceId)?.title||r.sourceResourceId):'Inheritance source unresolved';
 const source=r.sourceResourceId;const all=audit.grants.filter(g=>g.resourceId===(source||r.id));const grants=all.filter(g=>filter==='all'||filter==='external'&&/guest|#ext#/i.test(g.principal.type+' '+g.principal.loginName)||filter==='unresolved'&&hasGap(g.principal));
 document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));
 if(selectedGrant>=grants.length)selectedGrant=0;
 grants.forEach((g,i)=>{const b=el('button',undefined,'grant'+(i===selectedGrant?' selected':''));const label=el('span');label.append(el('strong',g.principal.title||g.principal.id),el('small',g.principal.type+(hasGap(g.principal)?' · membership gaps':'')));b.append(label,el('span',g.roles.map(r=>r.name).join(', ')+' →'));b.onclick=()=>{selectedGrant=i;renderResource()};$('grants').append(b)});
 const g=grants[selectedGrant];if(!g){$('grants').append(el('p',all.length?'No grants match this filter.':'No grants recorded. Check coverage; absence does not establish no access.'));$('principal').textContent='No selected grant';$('principalMeta').textContent='';$('path').textContent=r.title;$('membershipNote').textContent='Coverage determines whether evidence is complete.';return}
 $('principal').textContent=g.principal.title||g.principal.id;$('principalMeta').textContent=g.principal.type+' · '+g.roles.map(r=>r.name).join(', ');$('path').textContent=(r.title||r.id)+(source!==r.id?' → inherited source':'')+' → '+(g.principal.title||g.principal.id);showPrincipal($('members'),g.principal);$('membershipNote').textContent='Observed membership paths. Null identities, hidden memberships and service-principal omissions remain explicit limitations.';
}
function renderAudit(){
 document.querySelector('.top').replaceChildren(el('b',audit.scope.siteUrl),el('span',audit.synthetic?'Synthetic sample · offline':'Imported audit · offline','pill'));
 const gaps=audit.coverage.filter(c=>c.state!=='observed');const values=[[audit.resources.length,'Resources collected'],[audit.grants.length,'Observed grant assignments'],[audit.sharePointGroups.length+audit.directoryGroups.length,'Membership collections'],[gaps.length,'Coverage limitations']];document.querySelector('.stats').replaceChildren(...values.map(([n,t])=>{const d=el('div',undefined,'stat');d.append(el('strong',n),el('small',t));return d}));document.querySelector('.banner span').textContent='Partial evidence · '+gaps.length+' reported coverage limitations. Identity detail gaps may also remain.';
 const cov=document.querySelector('#coverage .empty');cov.replaceChildren(el('h2','Coverage is part of the evidence.'));for(const c of audit.coverage)cov.append(el('p',c.operation+' · '+c.state+' · '+c.reason));
 const ov=document.querySelector('#overview .empty');ov.replaceChildren(el('h2','Collected SharePoint inventory'),el('p',audit.scope.depth),el('p','Imported snapshot only. This interface does not sign in or alter tenant data.'));
 document.querySelector('.footer').replaceChildren(el('span','Snapshot · '+audit.completedAt),el('span','Local viewer · no network requests'));
 document.querySelector('#exports .empty p').textContent='Export this loaded snapshot. JSON is canonical; other formats include grants, membership and coverage.';$('exportDialog').querySelector('h2').textContent='Export loaded snapshot';$('exportDialog').querySelector('p').textContent='Downloads contain the loaded evidence and may include tenant identities.';renderTree();renderResource();
}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function exportRows(){const rows=[['kind','resource','principal','role or relationship','state','detail']];for(const r of audit.resources)rows.push(['resource',r.url,r.title,r.hasUniqueRoleAssignments?'unique':'inherited','observed',r.sourceResourceId]);for(const g of audit.grants)rows.push(['grant',g.resourceId,g.principal.title||g.principal.id,g.roles.map(r=>r.name).join('; '),'observed',g.principal.loginName]);for(const g of audit.sharePointGroups){rows.push(['group','',g.id,'SharePoint members',g.state,'']);for(const m of g.members)rows.push(['membership','',g.id,'member',g.state,m.title||m.loginName||m.id])}for(const g of audit.directoryGroups){rows.push(['group','',g.id,g.relationship||'members',g.state,g.reason]);for(const m of g.members)rows.push(['membership','',g.id,g.relationship||'members',g.state,[m.displayName,m.userPrincipalName,m.id].filter(Boolean).join(' · ')])}for(const c of audit.coverage)rows.push(['coverage',c.operation,'','',c.state,c.reason]);return rows}
function download(format){let text,mime;const json=JSON.stringify(audit,null,2);if(format==='JSON'){text=json;mime='application/json'}else if(format==='CSV'){const cell=s=>'"'+String(s??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';text=exportRows().map(r=>r.map(cell).join(',')).join('\r\n');mime='text/csv'}else if(format==='XML'){text='<?xml version="1.0" encoding="UTF-8"?><canopySnapshot encoding="json">'+escape(json)+'</canopySnapshot>';mime='application/xml'}else{text='<!doctype html><html lang="en"><meta charset="utf-8"><title>365Canopy audit</title><h1>365Canopy audit</h1><p>Partial evidence · '+escape(audit.scope.siteUrl)+'</p><table border="1">'+exportRows().map(r=>'<tr>'+r.map(v=>'<td>'+escape(v)+'</td>').join('')+'</tr>').join('')+'</table></html>';mime='text/html'}const link=el('a'),url=URL.createObjectURL(new Blob([text],{type:mime+';charset=utf-8'}));link.href=url;link.download='365Canopy-audit.'+format.toLowerCase();link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
for(const id of ['exportButtons','dialogButtons']){$(id).replaceChildren();for(const f of ['JSON','CSV','XML','HTML']){const b=el('button','↓ '+f);b.onclick=()=>download(f);$(id).append(b)}}
renderAudit();
