using System.Diagnostics;
using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Media.Animation;
using Microsoft.Win32;

namespace Canopy.Desktop;
public static class App
{
    [STAThread] public static int Main(string[] args)
    {
        var app=new Application();
        if(args.Length>0 && args[0]=="--smoke-test") { var w=new MainWindow(); w.LoadAudit(MainWindow.Sample); if(w.ResourceCount!=6||!w.ResultsSelected||!w.ConnectionFieldsEmpty) return 1; File.WriteAllText(args[1],"Desktop startup, blank connection fields, snapshot import and automatic Results navigation passed."); return 0; }
        var window=new MainWindow();
        if(args.Length==2 && args[0]=="--audit-smoke")window.Loaded+=async(_,_)=>{try{Directory.CreateDirectory(args[1]);await window.RunAudit();window.SaveSmoke(args[1]);app.Shutdown(window.ResourceCount>0?0:1);}catch{app.Shutdown(1);}};
        if(args.Length==3 && args[0]=="--preview-smoke")window.Loaded+=async(_,_)=>{try{window.LoadAudit(File.ReadAllText(args[1]));await Task.Delay(500);window.SaveSmoke(args[2]);app.Shutdown(0);}catch{app.Shutdown(1);}};
        if(args.Length==2 && (args[0]=="--audit-preview"||args[0]=="--audit-preview-light"||args[0]=="--wait-preview"))window.Loaded+=async(_,_)=>{window.LoadAudit(MainWindow.Sample);window.ShowPage("Audit");if(args[0]=="--wait-preview")window.PreviewWait();if(args[0]=="--audit-preview-light")window.SetAppearance("Light");await Task.Delay(500);window.SaveSmoke(args[1]);app.Shutdown(0);};
        if(args.Length==2&&args[0]=="--dependency-preview")window.Loaded+=(_,_)=>window.PreviewDependency(args[1]);
        app.Run(window);return 0;
    }
}
public sealed class MainWindow : Window
{
    readonly TextBox site=new(), tenant=new(), client=new(), library=new(), search=new();
    readonly CheckBox recursive=new(){Content="Include recursive folders",IsChecked=true}, files=new(){Content="Include file-level permissions review",IsChecked=false};
    readonly TreeView tree=new(); readonly StackPanel grants=new(),members=new(); readonly TextBlock status=new(){Text="Connect through Microsoft sign-in when you run an audit. No tenant connection yet.",TextWrapping=TextWrapping.Wrap},resourceTitle=new(){FontSize=23},resourceNote=new(){TextWrapping=TextWrapping.Wrap};
    readonly Button setup=new(){Content="Set up audit dependency…"};
    static string DependencyHome=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"365Canopy","modules","PnP.PowerShell","3.4.1");
    static bool DependencyReady { get { try { return File.Exists(Path.Combine(DependencyHome,"PnP.PowerShell.psd1"))&&File.ReadAllText(Path.Combine(DependencyHome,".canopy-ready")).Trim()=="82062BD1DA5464BFFAC78113ED85355C42225FBACE5CB5681E759C45A1B2DEB6"; } catch { return false; } } }
    readonly Button run=new(){Content="Run administrator audit"},cancel=new(){Content="Cancel audit",IsEnabled=false}; readonly ComboBox theme=new(){ItemsSource=new[]{"System","Light","Dark"},SelectedIndex=0};
    readonly TextBox coverage=new(){IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};
    JsonObject? audit;JsonObject? selected;Process? process;bool busy;
    readonly ContentControl pageHost=new();readonly Dictionary<string,FrameworkElement> pages=new();readonly Dictionary<string,Button> navigation=new();string currentPage="Audit";
    readonly ThemeService themes=new();readonly SiteProfileStore profileStore=new();List<SiteProfile> profiles=new();bool profilesAvailable=true;
    readonly ComboBox savedSites=new(){DisplayMemberPath="Name",MinWidth=220};readonly TextBox profileName=new(){MaxLength=120};
    readonly TextBlock pageTitle=new(){FontSize=28,FontWeight=FontWeights.SemiBold},pageSubtitle=new(), reportSummary=new();readonly StackPanel connectionForm=new();
    readonly Expander connectionIds=new(){Header="Tenant and application IDs",IsExpanded=true};
    readonly List<Button> exportButtons=new();
    readonly TextBlock resultsSummary=new(){Text="Run or open an audit to explore permissions.",TextWrapping=TextWrapping.Wrap};
    readonly Image windTree=new(){Source=new BitmapImage(new Uri("pack://application:,,,/365Canopy;component/Assets/Canopy.png")),Height=90,Width=100,Visibility=Visibility.Collapsed,RenderTransformOrigin=new Point(.5,.9),RenderTransform=new RotateTransform()};
    public int ResourceCount=>Array("resources").Count;
    public bool ConnectionFieldsEmpty=>new[]{site,tenant,client,library}.All(input=>string.IsNullOrWhiteSpace(input.Text));
    public bool ResultsSelected=>currentPage=="Results";
    public MainWindow()
    {
        Icon=BitmapFrame.Create(new Uri("pack://application:,,,/365Canopy;component/Assets/Canopy.ico"));Title="365Canopy · SharePoint audit";Width=1380;Height=900;MinWidth=1080;MinHeight=720;FontFamily=new FontFamily("Segoe UI");FontSize=14;
        Application.Current.Resources.MergedDictionaries.Add(new ResourceDictionary{Source=new Uri("/365Canopy;component/Styles.xaml",UriKind.Relative)});themes.Set("System");SetResourceReference(BackgroundProperty,"PageBrush");SetResourceReference(ForegroundProperty,"InkBrush");
        var root=new Grid();root.ColumnDefinitions.Add(new(){Width=new GridLength(214)});root.ColumnDefinitions.Add(new());Content=root;
        var rail=new DockPanel{Margin=new Thickness(20,28,20,20)};var railBorder=new Border{Child=rail,BorderThickness=new Thickness(0,0,1,0)};railBorder.SetResourceReference(Border.BackgroundProperty,"CardBrush");railBorder.SetResourceReference(Border.BorderBrushProperty,"LineBrush");root.Children.Add(railBorder);
        var brand=new StackPanel{Margin=new Thickness(0,0,0,24)};DockPanel.SetDock(brand,Dock.Top);rail.Children.Add(brand);
        brand.Children.Add(new Image{Source=windTree.Source,Height=62,HorizontalAlignment=HorizontalAlignment.Left});brand.Children.Add(Text("365Canopy",22));brand.Children.Add(Muted("SHAREPOINT VISIBILITY",10));
        var footer=new StackPanel();DockPanel.SetDock(footer,Dock.Bottom);rail.Children.Add(footer);footer.Children.Add(Muted("Appearance",12));footer.Children.Add(theme);theme.SelectionChanged+=(_,_)=>themes.Set(theme.SelectedItem?.ToString()??"System");footer.Children.Add(Muted("Local audit · Export when ready",11));
        var links=new StackPanel();rail.Children.Add(links);foreach(string name in new[]{"Audit","Results","Coverage","Report"}){string target=name;var button=Button(name,()=>ShowPage(target));button.HorizontalContentAlignment=HorizontalAlignment.Left;button.Margin=new Thickness(0,0,0,8);button.Padding=new Thickness(16,12,16,12);links.Children.Add(button);navigation[name]=button;}var open=Button("Open audit JSON…",Import);open.Margin=new Thickness(0,20,0,0);links.Children.Add(open);
        var main=new Grid{Margin=new Thickness(28,26,28,20)};Grid.SetColumn(main,1);root.Children.Add(main);main.RowDefinitions.Add(new(){Height=GridLength.Auto});main.RowDefinitions.Add(new());main.RowDefinitions.Add(new(){Height=GridLength.Auto});var heading=new StackPanel{Margin=new Thickness(0,0,0,20)};heading.Children.Add(pageTitle);pageSubtitle.SetResourceReference(TextBlock.ForegroundProperty,"MutedBrush");heading.Children.Add(pageSubtitle);main.Children.Add(heading);Grid.SetRow(pageHost,1);main.Children.Add(pageHost);
        var statusBorder=new Border{Child=status,BorderThickness=new Thickness(0,1,0,0),Padding=new Thickness(0,14,0,0),Margin=new Thickness(0,12,0,0)};statusBorder.SetResourceReference(Border.BorderBrushProperty,"LineBrush");status.SetResourceReference(TextBlock.ForegroundProperty,"MutedBrush");System.Windows.Automation.AutomationProperties.SetLiveSetting(status,System.Windows.Automation.AutomationLiveSetting.Polite);Grid.SetRow(statusBorder,2);main.Children.Add(statusBorder);
        var auditPage=new StackPanel();pages["Audit"]=new ScrollViewer{Content=auditPage,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};
        var saved=new StackPanel();saved.Children.Add(Muted("Save a friendly name on this Windows account. Loading a site fills the form; Microsoft sign-in still happens when you run an audit.",12));
        savedSites.Height=38;profileName.Height=38;var pickerRow=new Grid();pickerRow.ColumnDefinitions.Add(new());pickerRow.ColumnDefinitions.Add(new(){Width=GridLength.Auto});pickerRow.Children.Add(savedSites);var load=Button("Load site",LoadProfile);load.Margin=new Thickness(12,0,0,0);Grid.SetColumn(load,1);pickerRow.Children.Add(load);saved.Children.Add(pickerRow);var saveRow=new Grid{Margin=new Thickness(0,12,0,0)};saveRow.ColumnDefinitions.Add(new());saveRow.ColumnDefinitions.Add(new(){Width=GridLength.Auto});saveRow.ColumnDefinitions.Add(new(){Width=GridLength.Auto});profileName.ToolTip="Friendly name, e.g. Demo sales site";System.Windows.Automation.AutomationProperties.SetName(profileName,"Friendly site name");saveRow.Children.Add(profileName);var save=Button("Save site",SaveProfile);save.Margin=new Thickness(12,0,0,0);Grid.SetColumn(save,1);saveRow.Children.Add(save);var forget=Button("Forget site",ForgetProfile);forget.Margin=new Thickness(12,0,0,0);Grid.SetColumn(forget,2);saveRow.Children.Add(forget);saved.Children.Add(Muted("Friendly name",12));saved.Children.Add(saveRow);connectionForm.Children.Add(Card(new Expander{Header="Saved sites - save or load a connection",Content=saved,IsExpanded=false}));
        var details=new StackPanel();details.Children.Add(Text("Site details",20));var form=new Grid();form.ColumnDefinitions.Add(new(){Width=new GridLength(2,GridUnitType.Star)});form.ColumnDefinitions.Add(new());form.RowDefinitions.Add(new(){Height=GridLength.Auto});AddField(form,"Site URL",site,0,0);AddField(form,"Document library",library,0,1);details.Children.Add(form);var ids=new Grid();ids.ColumnDefinitions.Add(new());ids.ColumnDefinitions.Add(new());ids.RowDefinitions.Add(new(){Height=GridLength.Auto});AddField(ids,"Tenant ID",tenant,0,0);AddField(ids,"Public client ID",client,0,1);connectionIds.Content=ids;connectionIds.Margin=new Thickness(0,8,0,0);details.Children.Add(connectionIds);connectionForm.Children.Add(Card(details));auditPage.Children.Add(connectionForm);
        setup.Click+=async(_,_)=>await SetupDependency();setup.Visibility=DependencyReady?Visibility.Collapsed:Visibility.Visible;auditPage.Children.Add(setup);
        var scope=new StackPanel();scope.Children.Add(Text("Audit scope",20));scope.Children.Add(recursive);scope.Children.Add(files);scope.Children.Add(Muted("File review is optional. It includes all returned folders and files in this library; no file contents are downloaded.",12));files.Checked+=(_,_)=>{recursive.IsChecked=true;recursive.IsEnabled=false;};files.Unchecked+=(_,_)=>recursive.IsEnabled=true;
        var actions=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,12,0,0)};run.SetResourceReference(Control.BorderBrushProperty,"AccentBrush");actions.Children.Add(run);actions.Children.Add(cancel);scope.Children.Add(actions);var scopeLayout=new Grid();scopeLayout.ColumnDefinitions.Add(new());scopeLayout.ColumnDefinitions.Add(new(){Width=new GridLength(120)});scopeLayout.Children.Add(scope);windTree.HorizontalAlignment=HorizontalAlignment.Right;windTree.VerticalAlignment=VerticalAlignment.Center;windTree.Margin=new Thickness(12,0,0,0);Grid.SetColumn(windTree,1);scopeLayout.Children.Add(windTree);run.Click+=async(_,_)=>await RunAudit();cancel.Click+=(_,_)=>CancelAudit();auditPage.Children.Add(Card(scopeLayout));
        var boundary=new Expander{Header="Access and privacy",Content=Muted("Microsoft handles administrator sign-in. Full Control consent is write-capable; the collector uses read operations. Saved sites contain connection metadata only. Audit evidence stays in memory until export.",12)};auditPage.Children.Add(boundary);
        var results=new DockPanel();pages["Results"]=results;var resultHeader=new StackPanel();DockPanel.SetDock(resultHeader,Dock.Top);results.Children.Add(resultHeader);resultHeader.Children.Add(resultsSummary);resultHeader.Children.Add(Muted("Search resource names or paths",12));search.Margin=new Thickness(0,4,0,16);System.Windows.Automation.AutomationProperties.SetName(search,"Search resource names or paths");search.TextChanged+=(_,_)=>RenderTree();resultHeader.Children.Add(search);
        var body=new Grid();body.ColumnDefinitions.Add(new(){Width=new GridLength(1.1,GridUnitType.Star)});body.ColumnDefinitions.Add(new(){Width=new GridLength(1.4,GridUnitType.Star)});body.ColumnDefinitions.Add(new(){Width=new GridLength(1.2,GridUnitType.Star)});results.Children.Add(body);
        var treePane=new DockPanel();var treeLabel=Text("Resources",16);DockPanel.SetDock(treeLabel,Dock.Top);treePane.Children.Add(treeLabel);treePane.Children.Add(tree);var treeCard=Card(treePane);treeCard.Margin=new Thickness(0,0,12,0);body.Children.Add(treeCard);VirtualizingStackPanel.SetIsVirtualizing(tree,true);VirtualizingStackPanel.SetVirtualizationMode(tree,VirtualizationMode.Recycling);tree.SelectedItemChanged+=(_,e)=>{if(e.NewValue is TreeViewItem item&&item.Tag is JsonObject r)ShowResource(r);};
        var middle=new StackPanel();middle.Children.Add(resourceTitle);middle.Children.Add(resourceNote);middle.Children.Add(grants);var middleCard=Card(new ScrollViewer{Content=middle,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});middleCard.Margin=new Thickness(0,0,12,0);Grid.SetColumn(middleCard,1);body.Children.Add(middleCard);var memberCard=Card(new ScrollViewer{Content=members,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});memberCard.Margin=new Thickness(0);Grid.SetColumn(memberCard,2);body.Children.Add(memberCard);
        coverage.SetResourceReference(Control.BackgroundProperty,"CardBrush");coverage.SetResourceReference(Control.ForegroundProperty,"InkBrush");pages["Coverage"]=Card(coverage);
        var report=new StackPanel();report.Children.Add(Card(reportSummary));report.Children.Add(ExportCard("HTML report","Readable permissions, membership paths and collection gaps. Opens offline in your browser and supports printing.","Export HTML report…","html"));report.Children.Add(ExportCard("CSV data","Resource, grant and membership rows for filtering and analysis.","Export CSV…","csv"));report.Children.Add(ExportCard("JSON evidence","The original audit snapshot. Reopen it in Canopy to continue reviewing.","Export JSON…","json"));report.Children.Add(Muted("Exports contain tenant identities and permissions. Share them only with the intended recipients.",12));pages["Report"]=new ScrollViewer{Content=report,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};
        reportSummary.Text="Run or open an audit before exporting a report.";RefreshProfiles();ShowPage("Audit");Closing+=(_,e)=>{if(busy){MessageBox.Show("Cancel the active operation before closing.");e.Cancel=true;}};Closed+=(_,_)=>themes.Dispose();
    }
    static Border Card(UIElement child){var card=new Border{Child=child,Padding=new Thickness(20),Margin=new Thickness(0,0,0,16),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8)};card.SetResourceReference(Border.BackgroundProperty,"CardBrush");card.SetResourceReference(Border.BorderBrushProperty,"LineBrush");return card;}
    static TextBlock Muted(string value,int size=14){var text=Text(value,size);text.SetResourceReference(TextBlock.ForegroundProperty,"MutedBrush");return text;}
    Border ExportCard(string title,string description,string action,string format){var content=new StackPanel();content.Children.Add(Text(title,20));content.Children.Add(Muted(description));var export=Button(action,()=>Export(format));export.IsEnabled=audit!=null;exportButtons.Add(export);content.Children.Add(export);return Card(content);}
    public void SetAppearance(string value){theme.SelectedItem=value;}
    public void ShowPage(string name){currentPage=name;pageHost.Content=pages[name];pageTitle.Text=name switch{"Audit"=>"Audit a SharePoint site","Results"=>"Permissions & people","Coverage"=>"Collection coverage",_=>"Export your audit"};pageSubtitle.Text=name switch{"Audit"=>"Choose a site and the scope you need. Microsoft handles sign-in.","Results"=>"Follow permission sources and group memberships. Missing evidence means unknown access.","Coverage"=>"See what was collected, what failed and what was outside the selected scope.",_=>"A readable report for your client, with the evidence behind it."};foreach(var item in navigation){item.Value.SetResourceReference(Control.BorderBrushProperty,item.Key==name?"AccentBrush":"LineBrush");item.Value.FontWeight=item.Key==name?FontWeights.SemiBold:FontWeights.Normal;}}
    void RefreshProfiles(){try{profiles=profileStore.Read();savedSites.ItemsSource=profiles;profilesAvailable=true;}catch{profilesAvailable=false;status.Text="Saved sites could not be read. The existing file was left untouched; enter connection details manually.";}}
    SiteProfile CurrentProfile()=>new SiteProfile(profileName.Text,site.Text,tenant.Text,client.Text,library.Text,files.IsChecked==true,recursive.IsChecked==true).Validate();
    void LoadProfile(){if(busy)return;if(savedSites.SelectedItem is not SiteProfile p){status.Text="Choose a saved site first.";return;}site.Text=p.SiteUrl;tenant.Text=p.TenantId;client.Text=p.ClientId;library.Text=p.LibraryName;profileName.Text=p.Name;files.IsChecked=p.IncludeFiles;recursive.IsChecked=p.IncludeFiles||p.RecursiveFolders;connectionIds.IsExpanded=false;status.Text="Loaded "+p.Name+". Review the scope, then run an administrator audit.";}
    void SaveProfile(){if(busy)return;if(!profilesAvailable){MessageBox.Show("Saved sites are unavailable. The existing file will not be overwritten.");return;}try{var p=CurrentProfile();var next=profileStore.Read();var existing=next.FirstOrDefault(x=>x.Name.Equals(p.Name,StringComparison.OrdinalIgnoreCase));if(existing!=null&&MessageBox.Show("Replace saved details for "+p.Name+"?","Save site",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;next.RemoveAll(x=>x.Name.Equals(p.Name,StringComparison.OrdinalIgnoreCase));next.Add(p);profileStore.Write(next);RefreshProfiles();savedSites.SelectedItem=profiles.FirstOrDefault(x=>x.Name==p.Name);status.Text="Saved "+p.Name+" locally, protected for this Windows account. No credentials or audit results were saved.";}catch(Exception e){MessageBox.Show(e is InvalidDataException?e.Message:"The site could not be saved. Existing saved sites were preserved.","Save site");}}
    void ForgetProfile(){if(busy)return;if(savedSites.SelectedItem is not SiteProfile p){status.Text="Choose a saved site first.";return;}if(MessageBox.Show("Remove "+p.Name+" from saved sites? This does not change SharePoint.","Forget site",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;try{var next=profileStore.Read();next.RemoveAll(x=>x.Name.Equals(p.Name,StringComparison.OrdinalIgnoreCase));profileStore.Write(next);RefreshProfiles();status.Text="Saved site removed. The current form and audit results were kept.";}catch{MessageBox.Show("The saved site could not be removed. Existing saved sites were preserved.");}}
    void CancelAudit(){if(process is {HasExited:false})process.Kill(true);status.Text="Operation cancelled. The isolated process was stopped.";}
    static TextBlock Text(string text,int size=14)=>new(){Text=text,FontSize=size,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,6,0,6)};
    static Button Button(string text,Action click){var b=new Button{Content=new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap},Margin=new Thickness(0,0,8,8)};b.Click+=(_,_)=>click();return b;}
    static void AddField(Grid grid,string label,TextBox input,int row,int col){var p=new StackPanel{Margin=new Thickness(0,0,12,8)};p.Children.Add(Text(label,12));input.Padding=new Thickness(8);p.Children.Add(input);Grid.SetRow(p,row);Grid.SetColumn(p,col);grid.Children.Add(p);}
    JsonArray Array(string name)=>audit?[name] as JsonArray??new();
    static string S(JsonNode? n,string key)=>n?[key]?.ToString()??"";
    static bool B(JsonNode? n,string key)=>n?[key]?.GetValue<bool>()??false;
    public void LoadAudit(string json)
    {
        if(json.Length>100*1024*1024)throw new InvalidDataException("Snapshot exceeds 100 MB.");
        var next=JsonNode.Parse(json) as JsonObject??throw new InvalidDataException("Invalid JSON object.");
        if(S(next,"schemaVersion")!="0.2-delegated")throw new InvalidDataException("Expected a 0.2-delegated snapshot.");
        foreach(var key in new[]{"resources","grants","sharePointGroups","directoryGroups","coverage"})if(next[key] is not JsonArray a||a.Count>250000)throw new InvalidDataException("Invalid collection: "+key);
        var ids=new HashSet<string>();foreach(var r in (JsonArray)next["resources"]!)if(r is not JsonObject||!ids.Add(S(r,"id"))||S(r,"id")=="")throw new InvalidDataException("Invalid resource IDs.");
        foreach(var r in (JsonArray)next["resources"]!){if(r!["hasUniqueRoleAssignments"] is not null && (r["hasUniqueRoleAssignments"] is not JsonValue v||!v.TryGetValue<bool>(out _)))throw new InvalidDataException("Invalid inheritance flag.");}
        foreach(var g in (JsonArray)next["grants"]!){if(g is not JsonObject||g["principal"] is not JsonObject||g["roles"] is not JsonArray roles||roles.Any(r=>r is not JsonObject))throw new InvalidDataException("Invalid grant.");}
        foreach(var key in new[]{"sharePointGroups","directoryGroups"})foreach(var g in (JsonArray)next[key]!){if(g is not JsonObject||g["members"] is not JsonArray ms||ms.Count>50000||ms.Any(m=>m is not JsonObject))throw new InvalidDataException("Invalid membership collection.");}
        if(((JsonArray)next["coverage"]!).Any(c=>c is not JsonObject))throw new InvalidDataException("Invalid coverage record.");
        audit=next;selected=null;RenderTree();coverage.Text=string.Join("\n\n",Array("coverage").Select(c=>S(c,"operation")+" · "+S(c,"state")+"\n"+S(c,"reason")));
        status.Text=$"{ResourceCount} resources · {Array("resources").Count(r=>S(r,"type")=="file")} files · {Array("grants").Count} grants · {(S(next,"state")=="completed"?"Collection completed for selected scope":"Collection has gaps — review Coverage")} · {S(next,"completedAt")}";if(Array("resources").FirstOrDefault() is JsonObject first)ShowResource(first);
        resultsSummary.Text=S(next["scope"],"siteUrl")+" · "+S(next["scope"],"library")+"\n"+status.Text;reportSummary.Text=resultsSummary.Text;foreach(var export in exportButtons)export.IsEnabled=true;ShowPage("Results");
    }
    void Import(){var d=new OpenFileDialog{Filter="Canopy audit (*.json)|*.json"};if(d.ShowDialog()==true)try{LoadAudit(File.ReadAllText(d.FileName));}catch(Exception e){MessageBox.Show(e.Message,"Import failed");}}
    void Export(string format){if(audit==null){MessageBox.Show("Run or import an audit first.");return;}var d=new SaveFileDialog{Filter=$"{format.ToUpperInvariant()} report|*.{format}",FileName="365Canopy-audit."+format};if(d.ShowDialog()==true)try{string text=format switch{"html"=>AuditReport.Html(audit),"csv"=>AuditReport.Csv(audit),_=>audit.ToJsonString(new(){WriteIndented=true})};File.WriteAllText(d.FileName,text,new System.Text.UTF8Encoding(format=="csv"));}catch(Exception e){MessageBox.Show(e.Message,"Export failed");}}
    void RenderTree()
    {
        tree.Items.Clear();var nodes=new Dictionary<string,TreeViewItem>();var resources=Array("resources").OfType<JsonObject>().ToList();var resourceMap=resources.ToDictionary(r=>S(r,"id"));
        foreach(var r in resources){var n=new TreeViewItem{Header=S(r,"title")+(r["hasUniqueRoleAssignments"]==null?" · unknown":B(r,"hasUniqueRoleAssignments")?" · unique":""),Tag=r,IsExpanded=resources.Count<500||S(r,"type") is "web" or "library",ToolTip=S(r,"url")};nodes[S(r,"id")]=n;}
        foreach(var r in resources){string parent=S(r,"parentResourceId");if(parent==""&&S(r,"type")=="library")parent=S(resources.FirstOrDefault(x=>S(x,"type")=="web"),"id");if(parent==""&&S(r,"type")=="folder")parent=S(resources.FirstOrDefault(x=>S(x,"type")=="library"),"id");var n=nodes[S(r,"id")];if(search.Text!=""){if((S(r,"url")+S(r,"title")).Contains(search.Text,StringComparison.OrdinalIgnoreCase))tree.Items.Add(n);}else if(parent!=S(r,"id")&&nodes.TryGetValue(parent,out var p)&&!WouldCycle(r,resourceMap))p.Items.Add(n);else tree.Items.Add(n);}
    }
    static bool WouldCycle(JsonObject r,Dictionary<string,JsonObject> nodes){var seen=new HashSet<string>{S(r,"id")};var parent=S(r,"parentResourceId");while(parent!=""){if(!seen.Add(parent))return true;parent=nodes.TryGetValue(parent,out var node)?S(node,"parentResourceId"):"";}return false;}
    void ShowResource(JsonObject r){selected=r;resourceTitle.Text=S(r,"title");var source=S(r,"sourceResourceId");var sourceNode=Array("resources").FirstOrDefault(n=>S(n,"id")==source);resourceNote.Text=S(r,"url")+"\n"+(r["hasUniqueRoleAssignments"]==null?"Permission inheritance unknown":B(r,"hasUniqueRoleAssignments")?"Unique permissions":"Inherited permissions")+"\nPermission source: "+(sourceNode==null?"Unresolved":S(sourceNode,"title"));grants.Children.Clear();members.Children.Clear();var found=Array("grants").OfType<JsonObject>().Where(g=>S(g,"resourceId")==source).ToList();foreach(var g in found){var p=g["principal"]!;var roles=string.Join(", ",((JsonArray)g["roles"]!).Select(x=>S(x,"name")));grants.Children.Add(Button(S(p,"title")+" · "+roles,()=>ShowPrincipal((JsonObject)p)));}if(found.Count==0){grants.Children.Add(Text("No grants recorded. Review coverage; this does not prove no access."));members.Children.Add(Text("People",20));members.Children.Add(Muted("Select a recorded grant to explore its membership. No grants were recorded for this permission source."));}else ShowPrincipal((JsonObject)found[0]["principal"]!);}
    void ShowPrincipal(JsonObject p){members.Children.Clear();members.Children.Add(Text("Access path",12));members.Children.Add(Text(S(p,"title"),20));members.Children.Add(Text("Observed memberships; policies may affect access.",12));AppendPrincipal(members,p,new HashSet<string>());}
    void AppendPrincipal(StackPanel panel,JsonNode p,HashSet<string> seen)
    {
        if(seen.Count>=200){panel.Children.Add(Text("Expansion depth limit reached."));return;}
        if(S(p,"type")=="SharePointGroup"){if(!seen.Add("sp:"+S(p,"id"))){panel.Children.Add(Text("Cycle · group already shown"));return;}var g=Array("sharePointGroups").FirstOrDefault(g=>S(g,"id")==S(p,"id"));panel.Children.Add(Text("Classic SharePoint group · "+S(g,"state")));if(g?["members"] is JsonArray ms)foreach(var m in ms){if(m==null)continue;var child=new StackPanel{Margin=new Thickness(14,0,0,0)};panel.Children.Add(child);child.Children.Add(Text(S(m,"title")));AppendPrincipal(child,m,new(seen));}else panel.Children.Add(Text("Members not collected."));return;}
        var match=System.Text.RegularExpressions.Regex.Match(S(p,"loginName"),@"^c:(?:0t\.c\|tenant\||0o\.c\|federateddirectoryclaimprovider\|)([\da-f-]{36})(_o)?$",System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        if(match.Success){AppendDirectory(panel,match.Groups[1].Value,match.Groups[2].Success?"owners":"members",seen);return;}panel.Children.Add(Text(S(p,"loginName") is {Length:>0} login?login:S(p,"id"),12));
    }
    void AppendDirectory(StackPanel panel,string id,string relationship,HashSet<string> seen){string key=id+":"+relationship;if(!seen.Add(key)){panel.Children.Add(Text("Cycle · group already shown"));return;}var g=Array("directoryGroups").FirstOrDefault(g=>S(g,"id").Equals(id,StringComparison.OrdinalIgnoreCase)&&(S(g,"relationship")==""?"members":S(g,"relationship"))==relationship);panel.Children.Add(Text((S(g,"displayName")==""?id:S(g,"displayName"))+" · "+relationship));if(g==null){panel.Children.Add(Text("Not collected · people unknown"));return;}panel.Children.Add(Text(S(g,"state")+" · "+S(g,"reason"),11));if(g["members"] is JsonArray ms){if(ms.Count==0)panel.Children.Add(Text(S(g,"state")=="observed"?"No entries returned":"People unknown"));foreach(var m in ms){if(m==null)continue;var child=new StackPanel{Margin=new Thickness(14,0,0,0)};panel.Children.Add(child);if(S(m,"type")=="#microsoft.graph.group")AppendDirectory(child,S(m,"id"),"members",new(seen));else child.Children.Add(Text((S(m,"displayName")==""?S(m,"id"):S(m,"displayName"))+"\n"+(S(m,"userPrincipalName")==""?"Identity details unavailable":S(m,"userPrincipalName"))+"\nObject ID: "+S(m,"id"),12));}}
    }
    public void SaveSmoke(string directory){Directory.CreateDirectory(directory);if(audit==null)throw new InvalidOperationException("No audit loaded.");File.WriteAllText(Path.Combine(directory,"audit.json"),audit.ToJsonString(new(){WriteIndented=true}));UpdateLayout();var bmp=new RenderTargetBitmap((int)ActualWidth,(int)ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(this);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bmp));using var stream=File.Create(Path.Combine(directory,"desktop.png"));encoder.Save(stream);File.WriteAllText(Path.Combine(directory,"result.txt"),status.Text);}
    void SetWaitAnimation(bool active){windTree.Visibility=active?Visibility.Visible:Visibility.Collapsed;var transform=(RotateTransform)windTree.RenderTransform;transform.BeginAnimation(RotateTransform.AngleProperty,null);if(active&&SystemParameters.ClientAreaAnimation)transform.BeginAnimation(RotateTransform.AngleProperty,new DoubleAnimation(-4,4,TimeSpan.FromSeconds(1.5)){AutoReverse=true,RepeatBehavior=RepeatBehavior.Forever,EasingFunction=new SineEase{EasingMode=EasingMode.EaseInOut}});}
    public void PreviewWait(){SetWaitAnimation(true);run.IsEnabled=false;status.Text="Animation preview only - no tenant connection or audit.";}
    public async Task RunAudit()
    {
        if(busy)return;if(!DependencyReady){await SetupDependency();if(!DependencyReady)return;}try{new SiteProfile("Current site",site.Text,tenant.Text,client.Text,library.Text,files.IsChecked==true,recursive.IsChecked==true).Validate();}catch(InvalidDataException e){MessageBox.Show(e.Message,"Check site details");return;}
        string home=AppContext.BaseDirectory;string ps=Path.Combine(home,"runtime","powershell","pwsh.exe"),script=Path.Combine(home,"src","Canopy.Checkpoint","Desktop-Audit.ps1");if(!File.Exists(ps)||!File.Exists(script)){MessageBox.Show("Use the complete packaged build; the bundled collector/runtime is missing.");return;}
        busy=true;connectionForm.IsEnabled=false;files.IsEnabled=false;recursive.IsEnabled=false;run.IsEnabled=false;cancel.IsEnabled=true;status.Text="Microsoft sign-in / read-only collection in progress…";SetWaitAnimation(true);
        try{var start=new ProcessStartInfo(ps){WorkingDirectory=home,UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};foreach(var arg in new[]{"-NoLogo","-NoProfile","-File",script,"-SiteUrl",site.Text.Trim(),"-TenantId",tenant.Text.Trim(),"-ClientId",client.Text.Trim(),"-LibraryName",library.Text.Trim(),"-PnPModulePath",Path.Combine(DependencyHome,"PnP.PowerShell.psd1")})start.ArgumentList.Add(arg);if(recursive.IsChecked==true)start.ArgumentList.Add("-RecursiveFolders");if(files.IsChecked==true)start.ArgumentList.Add("-IncludeFiles");start.Environment["POWERSHELL_TELEMETRY_OPTOUT"]="1";start.Environment["POWERSHELL_UPDATECHECK"]="Off";process=Process.Start(start)!;var output=ReadCollectorOutput(process.StandardOutput);var error=process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();var line=await output;await error;if(process.ExitCode!=0||line==null)throw new InvalidOperationException("Collection interrupted or failed. No previous snapshot was replaced. Check prerequisites and complete Microsoft sign-in.");var payload=JsonNode.Parse(line[7..]);if(payload?["state"]?.ToString()=="failed"||(payload?["resources"] as JsonArray)?.Count==0)throw new InvalidOperationException("No resources were collected. Check Microsoft sign-in and site access; previous results were retained.");LoadAudit(line[7..]);}
        catch(Exception e){status.Text=e.Message;}finally{process?.Dispose();process=null;busy=false;connectionForm.IsEnabled=true;files.IsEnabled=true;recursive.IsEnabled=files.IsChecked!=true;run.IsEnabled=true;cancel.IsEnabled=false;SetWaitAnimation(false);}
    }
    Window CreateDependencyDialog()
    {
        var dialog=new Window{Title="One-time audit setup",Owner=this,Width=620,Height=520,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize};
        var content=new StackPanel{Margin=new Thickness(24)};dialog.Content=new ScrollViewer{Content=content,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};dialog.SetResourceReference(BackgroundProperty,"PageBrush");dialog.SetResourceReference(ForegroundProperty,"InkBrush");
        content.Children.Add(Text("Download the SharePoint audit dependency",22));
        content.Children.Add(Text("365Canopy downloads PnP.PowerShell 3.4.1 directly from PowerShell Gallery and verifies the reviewed archive hash. It is stored on this Windows account and reused for future audits. Internet access is needed for this setup. No tenant connection is made."));
        content.Children.Add(Text("The download includes Microsoft components with separate license terms. Review these before continuing:",12));
        foreach(var link in new[]{("PowerShell Gallery package and licenses","https://www.powershellgallery.com/packages/PnP.PowerShell/3.4.1"),("MSAL NativeInterop terms","https://www.nuget.org/packages/Microsoft.Identity.Client.NativeInterop/0.20.6/License"),("SharePoint client component terms","https://github.com/SharePoint/sp-dev-docs/blob/main/assets/MicrosoftSharePointClientComponentsEULA.docx")})content.Children.Add(Button(link.Item1,()=>Process.Start(new ProcessStartInfo(link.Item2){UseShellExecute=true})));
        content.Children.Add(Button("Download and set up",()=>{dialog.DialogResult=true;}));
        return dialog;
    }
    public void PreviewDependency(string directory)
    {
        var dialog=CreateDependencyDialog();dialog.Loaded+=async(_,_)=>{await Task.Delay(500);Directory.CreateDirectory(directory);dialog.UpdateLayout();var bmp=new RenderTargetBitmap((int)dialog.ActualWidth,(int)dialog.ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(dialog);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bmp));using(var stream=File.Create(Path.Combine(directory,"setup.png")))encoder.Save(stream);dialog.Close();Application.Current.Shutdown();};dialog.ShowDialog();
    }
    async Task SetupDependency()
    {
        if(busy)return;
        var dialog=CreateDependencyDialog();
        if(dialog.ShowDialog()!=true)return;
        string home=AppContext.BaseDirectory,ps=Path.Combine(home,"runtime","powershell","pwsh.exe"),script=Path.Combine(home,"src","Canopy.Checkpoint","Setup-Dependency.ps1");
        busy=true;setup.IsEnabled=false;run.IsEnabled=false;cancel.IsEnabled=true;SetWaitAnimation(true);status.Text="Downloading and verifying the audit dependency…";
        try{var start=new ProcessStartInfo(ps){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};foreach(var arg in new[]{"-NoLogo","-NoProfile","-File",script,"-Destination",DependencyHome})start.ArgumentList.Add(arg);start.Environment["POWERSHELL_TELEMETRY_OPTOUT"]="1";start.Environment["POWERSHELL_UPDATECHECK"]="Off";process=Process.Start(start)!;var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();var result=await output;await error;if(process.ExitCode!=0||!result.Contains("CANOPY_SETUP:ready")||!DependencyReady)throw new InvalidOperationException("Setup did not complete. Check your internet connection and retry; existing dependencies were preserved.");setup.Visibility=Visibility.Collapsed;status.Text="Audit dependency ready. Enter your site details and run an administrator audit.";}
        catch(Exception e){status.Text=e.Message;}finally{process?.Dispose();process=null;busy=false;setup.IsEnabled=true;run.IsEnabled=true;cancel.IsEnabled=false;SetWaitAnimation(false);}
    }
    async Task<string?> ReadCollectorOutput(StreamReader reader)
    {
        string? snapshot=null;
        while(await reader.ReadLineAsync() is {} line) {
            if(line.StartsWith("CANOPY_PROGRESS:"))status.Text=line[16..];
            else if(line.StartsWith("CANOPY:"))snapshot=line;
        }
        return snapshot;
    }
    public const string Sample="""
    {"schemaVersion":"0.2-delegated","completedAt":"synthetic","resources":[{"id":"w","type":"web","title":"Demo","url":"/demo","hasUniqueRoleAssignments":true,"sourceResourceId":"w"},{"id":"l","type":"library","title":"Docs","url":"/demo/docs","hasUniqueRoleAssignments":false,"sourceResourceId":"w"},{"id":"f","parentResourceId":"l","type":"folder","title":"Private","url":"/demo/docs/private","hasUniqueRoleAssignments":true,"sourceResourceId":"f"},{"id":"c","parentResourceId":"f","type":"folder","title":"Child","url":"/demo/docs/private/child","hasUniqueRoleAssignments":false,"sourceResourceId":"f"},{"id":"file","parentResourceId":"c","type":"file","title":"Inherited.docx","url":"/demo/docs/private/child/Inherited.docx","hasUniqueRoleAssignments":false,"sourceResourceId":"f"},{"id":"unknown","parentResourceId":"l","type":"file","title":"Unknown.pdf","url":"/demo/docs/Unknown.pdf","hasUniqueRoleAssignments":null,"sourceResourceId":null}],"grants":[],"sharePointGroups":[],"directoryGroups":[],"coverage":[]}
    """;
}
